export const OPENDRAWER = 'OPENDRAWER';
export const SHOWLOGO = 'SHOWLOGO';


export const CHANGEMETA_START = 'CHANGEMETA_START';
export const CHANGEMETA_SUCCESS = 'CHANGEMETA_SUCCESS';
export const CHANGEMETA_FAIL = 'CHANGEMETA_FAIL';

export const GETMETA_START = 'GETMETA_START';
export const GETMETA_SUCCESS = 'GETMETA_SUCCESS';
export const GETMETA_FAIL = 'GETMETA_FAIL';

export const LOADMORE_START = 'LOADMORE_START';
export const LOADMORE_SUCCESS = 'LOADMORE_SUCCESS';
export const LOADMORE_FAIL = 'LOADMORE_FAIL';

export const GETDETAIL_START = 'GETDETAIL_START';
export const GETDETAIL_SUCCESS = 'GETDETAIL_SUCCESS';
export const GETDETAIL_FAIL = 'GETDETAIL_FAIL';


export const REFRESH_START = 'REFRESH_START';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';

export const TOGGLEISLOADING = 'TOGGLEISLOADING';
export const TOGGLEISREFRESH = 'TOGGLEISREFRESH';

export const TOGGLEHASMORE = 'TOGGLEHASMORE';